name: RADSan Tests

on: push
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  test:
    name: Test // ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Generate
      run: make generate
    - name: Build
      run: make clang test-targets
    - name: Run unit tests
      run: make test
